// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyB0aDRPe-b86LjqEpbWqL2m3N2_H3Ora0M",
      authDomain: "commer-ef151.firebaseapp.com",
      databaseURL: "https://commer-ef151.firebaseio.com",
      projectId: "commer-ef151",
      storageBucket: "commer-ef151.appspot.com",
      messagingSenderId: "232181553323",
      appId: "1:232181553323:web:42281e8ed0eab5ba9b3fee",
      measurementId: "G-W2S3NL0B9H");

  /// Google Sign-In Client ID para Web
  /// Este ID debe coincidir con el configurado en web/index.html
  static const String googleSignInClientId =
      '232181553323-1qcbn5q2qoomdqv2lckbolclrs2tsaoe.apps.googleusercontent.com'; //'232181553323-eilihkps148nu7dp45cole4mlr7pkf1d.apps.googleusercontent.com';
}
