// Mocks generated by Mockito 5.4.6 from annotations
// in sellweb/test/helpers/mock_annotations.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i9;

import 'package:cloud_firestore/cloud_firestore.dart' as _i4;
import 'package:cloud_firestore_platform_interface/cloud_firestore_platform_interface.dart'
    as _i3;
import 'package:firebase_auth/firebase_auth.dart' as _i7;
import 'package:firebase_auth_platform_interface/firebase_auth_platform_interface.dart'
    as _i6;
import 'package:firebase_core/firebase_core.dart' as _i2;
import 'package:fpdart/fpdart.dart' as _i24;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:sellweb/core/errors/failures.dart' as _i25;
import 'package:sellweb/features/auth/domain/entities/account_profile.dart'
    as _i28;
import 'package:sellweb/features/auth/domain/entities/admin_profile.dart'
    as _i27;
import 'package:sellweb/features/auth/domain/entities/auth_profile.dart'
    as _i23;
import 'package:sellweb/features/auth/domain/repositories/account_repository.dart'
    as _i26;
import 'package:sellweb/features/auth/domain/repositories/auth_repository.dart'
    as _i22;
import 'package:sellweb/features/catalogue/data/datasources/catalogue_remote_datasource.dart'
    as _i18;
import 'package:sellweb/features/catalogue/data/models/category_model.dart'
    as _i21;
import 'package:sellweb/features/catalogue/data/models/product_catalogue_model.dart'
    as _i19;
import 'package:sellweb/features/catalogue/data/models/product_model.dart'
    as _i20;
import 'package:sellweb/features/catalogue/domain/entities/category.dart'
    as _i15;
import 'package:sellweb/features/catalogue/domain/entities/mark.dart' as _i17;
import 'package:sellweb/features/catalogue/domain/entities/product.dart'
    as _i12;
import 'package:sellweb/features/catalogue/domain/entities/product_catalogue.dart'
    as _i13;
import 'package:sellweb/features/catalogue/domain/entities/product_price.dart'
    as _i14;
import 'package:sellweb/features/catalogue/domain/entities/provider.dart'
    as _i16;
import 'package:sellweb/features/catalogue/domain/repositories/catalogue_repository.dart'
    as _i11;
import 'package:shared_preferences/src/shared_preferences_legacy.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseApp_0 extends _i1.SmartFake implements _i2.FirebaseApp {
  _FakeFirebaseApp_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSettings_1 extends _i1.SmartFake implements _i3.Settings {
  _FakeSettings_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCollectionReference_2<T extends Object?> extends _i1.SmartFake
    implements _i4.CollectionReference<T> {
  _FakeCollectionReference_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWriteBatch_3 extends _i1.SmartFake implements _i4.WriteBatch {
  _FakeWriteBatch_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoadBundleTask_4 extends _i1.SmartFake
    implements _i4.LoadBundleTask {
  _FakeLoadBundleTask_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuerySnapshot_5<T1 extends Object?> extends _i1.SmartFake
    implements _i4.QuerySnapshot<T1> {
  _FakeQuerySnapshot_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuery_6<T extends Object?> extends _i1.SmartFake
    implements _i4.Query<T> {
  _FakeQuery_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocumentReference_7<T extends Object?> extends _i1.SmartFake
    implements _i4.DocumentReference<T> {
  _FakeDocumentReference_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_8<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeActionCodeInfo_9 extends _i1.SmartFake
    implements _i6.ActionCodeInfo {
  _FakeActionCodeInfo_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserCredential_10 extends _i1.SmartFake
    implements _i7.UserCredential {
  _FakeUserCredential_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConfirmationResult_11 extends _i1.SmartFake
    implements _i7.ConfirmationResult {
  _FakeConfirmationResult_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirebaseFirestore].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseFirestore extends _i1.Mock implements _i4.FirebaseFirestore {
  MockFirebaseFirestore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseApp get app => (super.noSuchMethod(
        Invocation.getter(#app),
        returnValue: _FakeFirebaseApp_0(
          this,
          Invocation.getter(#app),
        ),
      ) as _i2.FirebaseApp);

  @override
  String get databaseURL => (super.noSuchMethod(
        Invocation.getter(#databaseURL),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#databaseURL),
        ),
      ) as String);

  @override
  String get databaseId => (super.noSuchMethod(
        Invocation.getter(#databaseId),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#databaseId),
        ),
      ) as String);

  @override
  _i3.Settings get settings => (super.noSuchMethod(
        Invocation.getter(#settings),
        returnValue: _FakeSettings_1(
          this,
          Invocation.getter(#settings),
        ),
      ) as _i3.Settings);

  @override
  set app(_i2.FirebaseApp? _app) => super.noSuchMethod(
        Invocation.setter(
          #app,
          _app,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set databaseURL(String? _databaseURL) => super.noSuchMethod(
        Invocation.setter(
          #databaseURL,
          _databaseURL,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set databaseId(String? _databaseId) => super.noSuchMethod(
        Invocation.setter(
          #databaseId,
          _databaseId,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set settings(_i3.Settings? settings) => super.noSuchMethod(
        Invocation.setter(
          #settings,
          settings,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<dynamic, dynamic> get pluginConstants => (super.noSuchMethod(
        Invocation.getter(#pluginConstants),
        returnValue: <dynamic, dynamic>{},
      ) as Map<dynamic, dynamic>);

  @override
  _i4.CollectionReference<Map<String, dynamic>> collection(
          String? collectionPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #collection,
          [collectionPath],
        ),
        returnValue: _FakeCollectionReference_2<Map<String, dynamic>>(
          this,
          Invocation.method(
            #collection,
            [collectionPath],
          ),
        ),
      ) as _i4.CollectionReference<Map<String, dynamic>>);

  @override
  _i4.WriteBatch batch() => (super.noSuchMethod(
        Invocation.method(
          #batch,
          [],
        ),
        returnValue: _FakeWriteBatch_3(
          this,
          Invocation.method(
            #batch,
            [],
          ),
        ),
      ) as _i4.WriteBatch);

  @override
  _i5.Future<void> clearPersistence() => (super.noSuchMethod(
        Invocation.method(
          #clearPersistence,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> enablePersistence(
          [_i3.PersistenceSettings? persistenceSettings]) =>
      (super.noSuchMethod(
        Invocation.method(
          #enablePersistence,
          [persistenceSettings],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i4.LoadBundleTask loadBundle(_i9.Uint8List? bundle) => (super.noSuchMethod(
        Invocation.method(
          #loadBundle,
          [bundle],
        ),
        returnValue: _FakeLoadBundleTask_4(
          this,
          Invocation.method(
            #loadBundle,
            [bundle],
          ),
        ),
      ) as _i4.LoadBundleTask);

  @override
  void useFirestoreEmulator(
    String? host,
    int? port, {
    bool? sslEnabled = false,
    bool? automaticHostMapping = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #useFirestoreEmulator,
          [
            host,
            port,
          ],
          {
            #sslEnabled: sslEnabled,
            #automaticHostMapping: automaticHostMapping,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i4.QuerySnapshot<T>> namedQueryWithConverterGet<T>(
    String? name, {
    _i3.GetOptions? options = const _i3.GetOptions(),
    required _i4.FromFirestore<T>? fromFirestore,
    required _i4.ToFirestore<T>? toFirestore,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #namedQueryWithConverterGet,
          [name],
          {
            #options: options,
            #fromFirestore: fromFirestore,
            #toFirestore: toFirestore,
          },
        ),
        returnValue:
            _i5.Future<_i4.QuerySnapshot<T>>.value(_FakeQuerySnapshot_5<T>(
          this,
          Invocation.method(
            #namedQueryWithConverterGet,
            [name],
            {
              #options: options,
              #fromFirestore: fromFirestore,
              #toFirestore: toFirestore,
            },
          ),
        )),
      ) as _i5.Future<_i4.QuerySnapshot<T>>);

  @override
  _i5.Future<_i4.QuerySnapshot<Map<String, dynamic>>> namedQueryGet(
    String? name, {
    _i3.GetOptions? options = const _i3.GetOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #namedQueryGet,
          [name],
          {#options: options},
        ),
        returnValue: _i5.Future<_i4.QuerySnapshot<Map<String, dynamic>>>.value(
            _FakeQuerySnapshot_5<Map<String, dynamic>>(
          this,
          Invocation.method(
            #namedQueryGet,
            [name],
            {#options: options},
          ),
        )),
      ) as _i5.Future<_i4.QuerySnapshot<Map<String, dynamic>>>);

  @override
  _i4.Query<Map<String, dynamic>> collectionGroup(String? collectionPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #collectionGroup,
          [collectionPath],
        ),
        returnValue: _FakeQuery_6<Map<String, dynamic>>(
          this,
          Invocation.method(
            #collectionGroup,
            [collectionPath],
          ),
        ),
      ) as _i4.Query<Map<String, dynamic>>);

  @override
  _i5.Future<void> disableNetwork() => (super.noSuchMethod(
        Invocation.method(
          #disableNetwork,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i4.DocumentReference<Map<String, dynamic>> doc(String? documentPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #doc,
          [documentPath],
        ),
        returnValue: _FakeDocumentReference_7<Map<String, dynamic>>(
          this,
          Invocation.method(
            #doc,
            [documentPath],
          ),
        ),
      ) as _i4.DocumentReference<Map<String, dynamic>>);

  @override
  _i5.Future<void> enableNetwork() => (super.noSuchMethod(
        Invocation.method(
          #enableNetwork,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<void> snapshotsInSync() => (super.noSuchMethod(
        Invocation.method(
          #snapshotsInSync,
          [],
        ),
        returnValue: _i5.Stream<void>.empty(),
      ) as _i5.Stream<void>);

  @override
  _i5.Future<T> runTransaction<T>(
    _i4.TransactionHandler<T>? transactionHandler, {
    Duration? timeout = const Duration(seconds: 30),
    int? maxAttempts = 5,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #runTransaction,
          [transactionHandler],
          {
            #timeout: timeout,
            #maxAttempts: maxAttempts,
          },
        ),
        returnValue: _i8.ifNotNull(
              _i8.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #runTransaction,
                  [transactionHandler],
                  {
                    #timeout: timeout,
                    #maxAttempts: maxAttempts,
                  },
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_8<T>(
              this,
              Invocation.method(
                #runTransaction,
                [transactionHandler],
                {
                  #timeout: timeout,
                  #maxAttempts: maxAttempts,
                },
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i5.Future<void> terminate() => (super.noSuchMethod(
        Invocation.method(
          #terminate,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> waitForPendingWrites() => (super.noSuchMethod(
        Invocation.method(
          #waitForPendingWrites,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setIndexConfiguration({
    required List<_i3.Index>? indexes,
    List<_i3.FieldOverrides>? fieldOverrides,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setIndexConfiguration,
          [],
          {
            #indexes: indexes,
            #fieldOverrides: fieldOverrides,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setIndexConfigurationFromJSON(String? json) =>
      (super.noSuchMethod(
        Invocation.method(
          #setIndexConfigurationFromJSON,
          [json],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [FirebaseAuth].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAuth extends _i1.Mock implements _i7.FirebaseAuth {
  MockFirebaseAuth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseApp get app => (super.noSuchMethod(
        Invocation.getter(#app),
        returnValue: _FakeFirebaseApp_0(
          this,
          Invocation.getter(#app),
        ),
      ) as _i2.FirebaseApp);

  @override
  set app(_i2.FirebaseApp? _app) => super.noSuchMethod(
        Invocation.setter(
          #app,
          _app,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set tenantId(String? tenantId) => super.noSuchMethod(
        Invocation.setter(
          #tenantId,
          tenantId,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set customAuthDomain(String? customAuthDomain) => super.noSuchMethod(
        Invocation.setter(
          #customAuthDomain,
          customAuthDomain,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<dynamic, dynamic> get pluginConstants => (super.noSuchMethod(
        Invocation.getter(#pluginConstants),
        returnValue: <dynamic, dynamic>{},
      ) as Map<dynamic, dynamic>);

  @override
  _i5.Future<void> useAuthEmulator(
    String? host,
    int? port, {
    bool? automaticHostMapping = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #useAuthEmulator,
          [
            host,
            port,
          ],
          {#automaticHostMapping: automaticHostMapping},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> applyActionCode(String? code) => (super.noSuchMethod(
        Invocation.method(
          #applyActionCode,
          [code],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i6.ActionCodeInfo> checkActionCode(String? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkActionCode,
          [code],
        ),
        returnValue: _i5.Future<_i6.ActionCodeInfo>.value(_FakeActionCodeInfo_9(
          this,
          Invocation.method(
            #checkActionCode,
            [code],
          ),
        )),
      ) as _i5.Future<_i6.ActionCodeInfo>);

  @override
  _i5.Future<void> confirmPasswordReset({
    required String? code,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmPasswordReset,
          [],
          {
            #code: code,
            #newPassword: newPassword,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i7.UserCredential> createUserWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUserWithEmailAndPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue:
            _i5.Future<_i7.UserCredential>.value(_FakeUserCredential_10(
          this,
          Invocation.method(
            #createUserWithEmailAndPassword,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i5.Future<_i7.UserCredential>);

  @override
  _i5.Future<List<String>> fetchSignInMethodsForEmail(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchSignInMethodsForEmail,
          [email],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<_i7.UserCredential> getRedirectResult() => (super.noSuchMethod(
        Invocation.method(
          #getRedirectResult,
          [],
        ),
        returnValue:
            _i5.Future<_i7.UserCredential>.value(_FakeUserCredential_10(
          this,
          Invocation.method(
            #getRedirectResult,
            [],
          ),
        )),
      ) as _i5.Future<_i7.UserCredential>);

  @override
  bool isSignInWithEmailLink(String? emailLink) => (super.noSuchMethod(
        Invocation.method(
          #isSignInWithEmailLink,
          [emailLink],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Stream<_i7.User?> authStateChanges() => (super.noSuchMethod(
        Invocation.method(
          #authStateChanges,
          [],
        ),
        returnValue: _i5.Stream<_i7.User?>.empty(),
      ) as _i5.Stream<_i7.User?>);

  @override
  _i5.Stream<_i7.User?> idTokenChanges() => (super.noSuchMethod(
        Invocation.method(
          #idTokenChanges,
          [],
        ),
        returnValue: _i5.Stream<_i7.User?>.empty(),
      ) as _i5.Stream<_i7.User?>);

  @override
  _i5.Stream<_i7.User?> userChanges() => (super.noSuchMethod(
        Invocation.method(
          #userChanges,
          [],
        ),
        returnValue: _i5.Stream<_i7.User?>.empty(),
      ) as _i5.Stream<_i7.User?>);

  @override
  _i5.Future<void> sendPasswordResetEmail({
    required String? email,
    _i6.ActionCodeSettings? actionCodeSettings,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendPasswordResetEmail,
          [],
          {
            #email: email,
            #actionCodeSettings: actionCodeSettings,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> sendSignInLinkToEmail({
    required String? email,
    required _i6.ActionCodeSettings? actionCodeSettings,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendSignInLinkToEmail,
          [],
          {
            #email: email,
            #actionCodeSettings: actionCodeSettings,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setLanguageCode(String? languageCode) => (super.noSuchMethod(
        Invocation.method(
          #setLanguageCode,
          [languageCode],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setSettings({
    bool? appVerificationDisabledForTesting = false,
    String? userAccessGroup,
    String? phoneNumber,
    String? smsCode,
    bool? forceRecaptchaFlow,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSettings,
          [],
          {
            #appVerificationDisabledForTesting:
                appVerificationDisabledForTesting,
            #userAccessGroup: userAccessGroup,
            #phoneNumber: phoneNumber,
            #smsCode: smsCode,
            #forceRecaptchaFlow: forceRecaptchaFlow,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setPersistence(_i6.Persistence? persistence) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPersistence,
          [persistence],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i7.UserCredential> signInAnonymously() => (super.noSuchMethod(
        Invocation.method(
          #signInAnonymously,
          [],
        ),
        returnValue:
            _i5.Future<_i7.UserCredential>.value(_FakeUserCredential_10(
          this,
          Invocation.method(
            #signInAnonymously,
            [],
          ),
        )),
      ) as _i5.Future<_i7.UserCredential>);

  @override
  _i5.Future<_i7.UserCredential> signInWithCredential(
          _i6.AuthCredential? credential) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithCredential,
          [credential],
        ),
        returnValue:
            _i5.Future<_i7.UserCredential>.value(_FakeUserCredential_10(
          this,
          Invocation.method(
            #signInWithCredential,
            [credential],
          ),
        )),
      ) as _i5.Future<_i7.UserCredential>);

  @override
  _i5.Future<_i7.UserCredential> signInWithCustomToken(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithCustomToken,
          [token],
        ),
        returnValue:
            _i5.Future<_i7.UserCredential>.value(_FakeUserCredential_10(
          this,
          Invocation.method(
            #signInWithCustomToken,
            [token],
          ),
        )),
      ) as _i5.Future<_i7.UserCredential>);

  @override
  _i5.Future<_i7.UserCredential> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailAndPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue:
            _i5.Future<_i7.UserCredential>.value(_FakeUserCredential_10(
          this,
          Invocation.method(
            #signInWithEmailAndPassword,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i5.Future<_i7.UserCredential>);

  @override
  _i5.Future<_i7.UserCredential> signInWithEmailLink({
    required String? email,
    required String? emailLink,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailLink,
          [],
          {
            #email: email,
            #emailLink: emailLink,
          },
        ),
        returnValue:
            _i5.Future<_i7.UserCredential>.value(_FakeUserCredential_10(
          this,
          Invocation.method(
            #signInWithEmailLink,
            [],
            {
              #email: email,
              #emailLink: emailLink,
            },
          ),
        )),
      ) as _i5.Future<_i7.UserCredential>);

  @override
  _i5.Future<_i7.UserCredential> signInWithProvider(
          _i6.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithProvider,
          [provider],
        ),
        returnValue:
            _i5.Future<_i7.UserCredential>.value(_FakeUserCredential_10(
          this,
          Invocation.method(
            #signInWithProvider,
            [provider],
          ),
        )),
      ) as _i5.Future<_i7.UserCredential>);

  @override
  _i5.Future<_i7.ConfirmationResult> signInWithPhoneNumber(
    String? phoneNumber, [
    _i7.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithPhoneNumber,
          [
            phoneNumber,
            verifier,
          ],
        ),
        returnValue:
            _i5.Future<_i7.ConfirmationResult>.value(_FakeConfirmationResult_11(
          this,
          Invocation.method(
            #signInWithPhoneNumber,
            [
              phoneNumber,
              verifier,
            ],
          ),
        )),
      ) as _i5.Future<_i7.ConfirmationResult>);

  @override
  _i5.Future<_i7.UserCredential> signInWithPopup(_i6.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithPopup,
          [provider],
        ),
        returnValue:
            _i5.Future<_i7.UserCredential>.value(_FakeUserCredential_10(
          this,
          Invocation.method(
            #signInWithPopup,
            [provider],
          ),
        )),
      ) as _i5.Future<_i7.UserCredential>);

  @override
  _i5.Future<void> signInWithRedirect(_i6.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithRedirect,
          [provider],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> verifyPasswordResetCode(String? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyPasswordResetCode,
          [code],
        ),
        returnValue: _i5.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #verifyPasswordResetCode,
            [code],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> verifyPhoneNumber({
    String? phoneNumber,
    _i6.PhoneMultiFactorInfo? multiFactorInfo,
    required _i6.PhoneVerificationCompleted? verificationCompleted,
    required _i6.PhoneVerificationFailed? verificationFailed,
    required _i6.PhoneCodeSent? codeSent,
    required _i6.PhoneCodeAutoRetrievalTimeout? codeAutoRetrievalTimeout,
    String? autoRetrievedSmsCodeForTesting,
    Duration? timeout = const Duration(seconds: 30),
    int? forceResendingToken,
    _i6.MultiFactorSession? multiFactorSession,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyPhoneNumber,
          [],
          {
            #phoneNumber: phoneNumber,
            #multiFactorInfo: multiFactorInfo,
            #verificationCompleted: verificationCompleted,
            #verificationFailed: verificationFailed,
            #codeSent: codeSent,
            #codeAutoRetrievalTimeout: codeAutoRetrievalTimeout,
            #autoRetrievedSmsCodeForTesting: autoRetrievedSmsCodeForTesting,
            #timeout: timeout,
            #forceResendingToken: forceResendingToken,
            #multiFactorSession: multiFactorSession,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> revokeTokenWithAuthorizationCode(
          String? authorizationCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #revokeTokenWithAuthorizationCode,
          [authorizationCode],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> initializeRecaptchaConfig() => (super.noSuchMethod(
        Invocation.method(
          #initializeRecaptchaConfig,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i10.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() => (super.noSuchMethod(
        Invocation.method(
          #getKeys,
          [],
        ),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  Object? get(String? key) => (super.noSuchMethod(Invocation.method(
        #get,
        [key],
      )) as Object?);

  @override
  bool? getBool(String? key) => (super.noSuchMethod(Invocation.method(
        #getBool,
        [key],
      )) as bool?);

  @override
  int? getInt(String? key) => (super.noSuchMethod(Invocation.method(
        #getInt,
        [key],
      )) as int?);

  @override
  double? getDouble(String? key) => (super.noSuchMethod(Invocation.method(
        #getDouble,
        [key],
      )) as double?);

  @override
  String? getString(String? key) => (super.noSuchMethod(Invocation.method(
        #getString,
        [key],
      )) as String?);

  @override
  bool containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getStringList,
        [key],
      )) as List<String>?);

  @override
  _i5.Future<bool> setBool(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setDouble(
    String? key,
    double? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDouble,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setStringList(
    String? key,
    List<String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> commit() => (super.noSuchMethod(
        Invocation.method(
          #commit,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [CatalogueRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatalogueRepository extends _i1.Mock
    implements _i11.CatalogueRepository {
  MockCatalogueRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i4.QuerySnapshot<Object?>> getCatalogueStream(
          String? accountId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCatalogueStream,
          [accountId],
        ),
        returnValue: _i5.Stream<_i4.QuerySnapshot<Object?>>.empty(),
      ) as _i5.Stream<_i4.QuerySnapshot<Object?>>);

  @override
  _i5.Future<_i12.Product?> getPublicProductByCode(String? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPublicProductByCode,
          [code],
        ),
        returnValue: _i5.Future<_i12.Product?>.value(),
      ) as _i5.Future<_i12.Product?>);

  @override
  _i5.Future<void> addProductToCatalogue(
    _i13.ProductCatalogue? product,
    String? accountId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addProductToCatalogue,
          [
            product,
            accountId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> createPublicProduct(_i12.Product? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPublicProduct,
          [product],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> createPendingProduct(_i12.Product? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPendingProduct,
          [product],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> registerProductPrice(
    _i14.ProductPrice? productPrice,
    String? productCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerProductPrice,
          [
            productPrice,
            productCode,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> incrementSales(
    String? accountId,
    String? productId,
    double? quantity,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #incrementSales,
          [
            accountId,
            productId,
            quantity,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> decrementStock(
    String? accountId,
    String? productId,
    double? quantity,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #decrementStock,
          [
            accountId,
            productId,
            quantity,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateProductFavorite(
    String? accountId,
    String? productId,
    bool? isFavorite,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProductFavorite,
          [
            accountId,
            productId,
            isFavorite,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<List<_i15.Category>> getCategoriesStream(String? accountId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoriesStream,
          [accountId],
        ),
        returnValue: _i5.Stream<List<_i15.Category>>.empty(),
      ) as _i5.Stream<List<_i15.Category>>);

  @override
  _i5.Stream<List<_i16.Provider>> getProvidersStream(String? accountId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProvidersStream,
          [accountId],
        ),
        returnValue: _i5.Stream<List<_i16.Provider>>.empty(),
      ) as _i5.Stream<List<_i16.Provider>>);

  @override
  _i5.Stream<List<_i17.Mark>> getBrandsStream({String? country = 'ARG'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBrandsStream,
          [],
          {#country: country},
        ),
        returnValue: _i5.Stream<List<_i17.Mark>>.empty(),
      ) as _i5.Stream<List<_i17.Mark>>);

  @override
  _i5.Future<List<_i17.Mark>> searchBrands({
    required String? query,
    String? country = 'ARG',
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchBrands,
          [],
          {
            #query: query,
            #country: country,
            #limit: limit,
          },
        ),
        returnValue: _i5.Future<List<_i17.Mark>>.value(<_i17.Mark>[]),
      ) as _i5.Future<List<_i17.Mark>>);

  @override
  _i5.Future<List<_i17.Mark>> getPopularBrands({
    String? country = 'ARG',
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularBrands,
          [],
          {
            #country: country,
            #limit: limit,
          },
        ),
        returnValue: _i5.Future<List<_i17.Mark>>.value(<_i17.Mark>[]),
      ) as _i5.Future<List<_i17.Mark>>);

  @override
  _i5.Future<_i17.Mark?> getBrandById(
    String? id, {
    String? country = 'ARG',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBrandById,
          [id],
          {#country: country},
        ),
        returnValue: _i5.Future<_i17.Mark?>.value(),
      ) as _i5.Future<_i17.Mark?>);

  @override
  _i5.Future<void> createBrand(
    _i17.Mark? brand, {
    String? country = 'ARG',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBrand,
          [brand],
          {#country: country},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateBrand(
    _i17.Mark? brand, {
    String? country = 'ARG',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBrand,
          [brand],
          {#country: country},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i13.ProductCatalogue>> getProducts(String? accountId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [accountId],
        ),
        returnValue: _i5.Future<List<_i13.ProductCatalogue>>.value(
            <_i13.ProductCatalogue>[]),
      ) as _i5.Future<List<_i13.ProductCatalogue>>);

  @override
  _i5.Future<_i13.ProductCatalogue?> getProductById(
    String? accountId,
    String? productId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductById,
          [
            accountId,
            productId,
          ],
        ),
        returnValue: _i5.Future<_i13.ProductCatalogue?>.value(),
      ) as _i5.Future<_i13.ProductCatalogue?>);

  @override
  _i5.Future<void> createProduct(
    String? accountId,
    _i13.ProductCatalogue? product,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProduct,
          [
            accountId,
            product,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateProduct(
    String? accountId,
    _i13.ProductCatalogue? product,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProduct,
          [
            accountId,
            product,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteProduct(
    String? accountId,
    String? productId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [
            accountId,
            productId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i12.Product>> searchGlobalProducts(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchGlobalProducts,
          [query],
        ),
        returnValue: _i5.Future<List<_i12.Product>>.value(<_i12.Product>[]),
      ) as _i5.Future<List<_i12.Product>>);

  @override
  _i5.Future<List<_i15.Category>> getCategories(String? accountId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [accountId],
        ),
        returnValue: _i5.Future<List<_i15.Category>>.value(<_i15.Category>[]),
      ) as _i5.Future<List<_i15.Category>>);

  @override
  _i5.Future<void> updateStock(
    String? accountId,
    String? productId,
    double? newStock,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStock,
          [
            accountId,
            productId,
            newStock,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> incrementProductFollowers(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #incrementProductFollowers,
          [productId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> decrementProductFollowers(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #decrementProductFollowers,
          [productId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> createCategory({
    required String? accountId,
    required String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCategory,
          [],
          {
            #accountId: accountId,
            #name: name,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateCategory({
    required String? accountId,
    required String? categoryId,
    required String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [],
          {
            #accountId: accountId,
            #categoryId: categoryId,
            #name: name,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteCategory({
    required String? accountId,
    required String? categoryId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [],
          {
            #accountId: accountId,
            #categoryId: categoryId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> createProvider({
    required String? accountId,
    required String? name,
    String? phone,
    String? email,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProvider,
          [],
          {
            #accountId: accountId,
            #name: name,
            #phone: phone,
            #email: email,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateProvider({
    required String? accountId,
    required String? providerId,
    required String? name,
    String? phone,
    String? email,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProvider,
          [],
          {
            #accountId: accountId,
            #providerId: providerId,
            #name: name,
            #phone: phone,
            #email: email,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteProvider({
    required String? accountId,
    required String? providerId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProvider,
          [],
          {
            #accountId: accountId,
            #providerId: providerId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [CatalogueRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatalogueRemoteDataSource extends _i1.Mock
    implements _i18.CatalogueRemoteDataSource {
  MockCatalogueRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i19.ProductCatalogueModel>> getProducts(String? accountId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [accountId],
        ),
        returnValue: _i5.Future<List<_i19.ProductCatalogueModel>>.value(
            <_i19.ProductCatalogueModel>[]),
      ) as _i5.Future<List<_i19.ProductCatalogueModel>>);

  @override
  _i5.Future<_i19.ProductCatalogueModel?> getProductById(
    String? accountId,
    String? productId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductById,
          [
            accountId,
            productId,
          ],
        ),
        returnValue: _i5.Future<_i19.ProductCatalogueModel?>.value(),
      ) as _i5.Future<_i19.ProductCatalogueModel?>);

  @override
  _i5.Future<void> createProduct(
    String? accountId,
    _i19.ProductCatalogueModel? product,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProduct,
          [
            accountId,
            product,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateProduct(
    String? accountId,
    _i19.ProductCatalogueModel? product,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProduct,
          [
            accountId,
            product,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteProduct(
    String? accountId,
    String? productId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [
            accountId,
            productId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i20.ProductModel>> searchGlobalProducts(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchGlobalProducts,
          [query],
        ),
        returnValue:
            _i5.Future<List<_i20.ProductModel>>.value(<_i20.ProductModel>[]),
      ) as _i5.Future<List<_i20.ProductModel>>);

  @override
  _i5.Future<List<_i21.CategoryModel>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue:
            _i5.Future<List<_i21.CategoryModel>>.value(<_i21.CategoryModel>[]),
      ) as _i5.Future<List<_i21.CategoryModel>>);

  @override
  _i5.Future<void> updateStock(
    String? accountId,
    String? productId,
    int? newStock,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStock,
          [
            accountId,
            productId,
            newStock,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i22.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i23.AuthProfile?> get user => (super.noSuchMethod(
        Invocation.getter(#user),
        returnValue: _i5.Stream<_i23.AuthProfile?>.empty(),
      ) as _i5.Stream<_i23.AuthProfile?>);

  @override
  _i5.Future<_i24.Either<_i25.Failure, _i23.AuthProfile>> signInWithGoogle() =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue:
            _i5.Future<_i24.Either<_i25.Failure, _i23.AuthProfile>>.value(
                _i8.dummyValue<_i24.Either<_i25.Failure, _i23.AuthProfile>>(
          this,
          Invocation.method(
            #signInWithGoogle,
            [],
          ),
        )),
      ) as _i5.Future<_i24.Either<_i25.Failure, _i23.AuthProfile>>);

  @override
  _i5.Future<_i24.Either<_i25.Failure, _i23.AuthProfile>> signInSilently() =>
      (super.noSuchMethod(
        Invocation.method(
          #signInSilently,
          [],
        ),
        returnValue:
            _i5.Future<_i24.Either<_i25.Failure, _i23.AuthProfile>>.value(
                _i8.dummyValue<_i24.Either<_i25.Failure, _i23.AuthProfile>>(
          this,
          Invocation.method(
            #signInSilently,
            [],
          ),
        )),
      ) as _i5.Future<_i24.Either<_i25.Failure, _i23.AuthProfile>>);

  @override
  _i5.Future<_i24.Either<_i25.Failure, _i23.AuthProfile>> signInAnonymously() =>
      (super.noSuchMethod(
        Invocation.method(
          #signInAnonymously,
          [],
        ),
        returnValue:
            _i5.Future<_i24.Either<_i25.Failure, _i23.AuthProfile>>.value(
                _i8.dummyValue<_i24.Either<_i25.Failure, _i23.AuthProfile>>(
          this,
          Invocation.method(
            #signInAnonymously,
            [],
          ),
        )),
      ) as _i5.Future<_i24.Either<_i25.Failure, _i23.AuthProfile>>);

  @override
  _i5.Future<_i24.Either<_i25.Failure, void>> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<_i24.Either<_i25.Failure, void>>.value(
            _i8.dummyValue<_i24.Either<_i25.Failure, void>>(
          this,
          Invocation.method(
            #signOut,
            [],
          ),
        )),
      ) as _i5.Future<_i24.Either<_i25.Failure, void>>);
}

/// A class which mocks [AccountRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountRepository extends _i1.Mock implements _i26.AccountRepository {
  MockAccountRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i27.AdminProfile>> getUserAccounts(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserAccounts,
          [email],
        ),
        returnValue:
            _i5.Future<List<_i27.AdminProfile>>.value(<_i27.AdminProfile>[]),
      ) as _i5.Future<List<_i27.AdminProfile>>);

  @override
  _i5.Future<_i28.AccountProfile?> getAccount(String? accountId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccount,
          [accountId],
        ),
        returnValue: _i5.Future<_i28.AccountProfile?>.value(),
      ) as _i5.Future<_i28.AccountProfile?>);

  @override
  _i5.Future<void> saveSelectedAccountId(String? accountId) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSelectedAccountId,
          [accountId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getSelectedAccountId() => (super.noSuchMethod(
        Invocation.method(
          #getSelectedAccountId,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> removeSelectedAccountId() => (super.noSuchMethod(
        Invocation.method(
          #removeSelectedAccountId,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
